import type { NextPage } from 'next';
import Head from 'next/head';
import { useDispatch } from 'react-redux';
import { toggleTheme } from 'store/user/user.slice';

const Home: NextPage = () => {
  const dispatch = useDispatch();
  return (
    <div>
      <Head>
        <title>My Next Boilerplate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>Hello World</main>
      <button onClick={() => dispatch(toggleTheme())}>Toggle Theme</button>
    </div>
  );
};

export default Home;
