import type { NextPage } from 'next';
import Head from 'next/head';
import { useDispatch } from 'react-redux';
import { toggleTheme } from 'store/user/user.slice';

const Home: NextPage = () => {
  const dispatch = useDispatch();
  return (
    <main>
      <Head>
        <title>Rush Next Boilerplate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <p>Boilerplate for someone who is rushing to complete an MVP</p>
      </header>
      <div>
        <h2>Main Stacks</h2>
        <ul>
          <li>NextJS</li>
          <li>TypeScript</li>
          <li>Redux Toolkit</li>
          <li>Styled Component</li>
        </ul>
        <h2>Supplementary Packages</h2>
        <ul>
          <li>JSON-Server</li>
          <li>React Hook Form</li>
          <li>Concurrently</li>
          <li>React Icons</li>
          <li>Axios</li>
          <li>Redux Saga</li>
          <li>Redux Next Wrapper</li>
        </ul>
        <h2>What&apos;s already been setup</h2>
        <ul>
          <li>
            Next-Redux-Wrapper wrapping _app.tsx and Redux store for dummy user
            and preference, just waiting to be populate
          </li>
          <li>
            Plop code generator for Redux Store, Pages and Module Component
            Boilerplate files. Just run few CLIs and its ready to be used
          </li>
          <li>
            Styled Components GlobalStyles and custom light & dark theme (feel
            free to build your own design system)
          </li>
          <li>
            Concurrently that runs next and JSON Server concurrently with a
            single CLI command, just run dev
          </li>
          <li>Example of Todo List using the Mockup API from JSON Server</li>
          <li>Simplified Layout for Navbar, Main & Footer</li>
          <li>Absolute Imports</li>
          <li>Roboto Font</li>
        </ul>
        <h2>Coming Soon</h2>
        <ul>
          <li>
            CLI Tool to auto create files and folders for Redux Store, Pages,
            Components
          </li>
        </ul>
      </div>
    </main>
  );
};

export default Home;
